### ISSUE TITLE
DISCUSS: Is the keyword whitelist helpful?

### ISSUE THREAD

**Issue by nathwill** [nathwill/chef-haproxy-ng#12]
I've been contemplating alternative ways to manage config validation that would eliminate the need to maintain a keyword whitelist, but wanted to open the topic for feedback before deciding how to proceed.

So... pros/cons:

Pros: the nice thing about having the whitelist is being able to fail hard as early as possible (compile time), when dealing with an invalid configuration.

Cons: it's somewhat fragile, and not specific to the version of haproxy in use. Since some keywords only apply to the latest version, or may have been deprecated in a newer version, it's not guaranteed to catch errors, and it may be artificially restrictive if haproxy supports keywords that aren't explicly listed.

Alternatives: I'd like to do something more like the sudo cookbook's validate_fragment!, since this would eliminate the burden of trying to maintain a 1:1 mapping of keywords, and would be executed against the installed haproxy, and thus adaptive to the haproxy version in use. The downside would be that it would shift validation into the converge stage of the chef run, so feedback would be slightly delayed.

Thoughts?

**Comment by nathwill** [comment]
hmmm, it might actually be nice to do both, with an attribute to enable/disable compile-time validation... seems like a nice middle ground, with an easy option to disable if it turns out to be overly restrictive... i'll start fiddling with some code and see how reasonable this would be in practice.

**Comment by vkhatri** [comment]
@nathwill IMHO, it would be wonderful to have it and option to enable/disable will work for everyone.

chef 12 added `verify` (https://docs.chef.io/resource_template.html) resource attribute which we can leverage to validate haproxy config (but i have not tested it myself), for chef 11 we need to do the magic around the template (something i was trying to do for openssh cookbook - https://github.com/opscode-cookbooks/openssh/pull/48/files).

**Comment by nathwill** [comment]
@vkhatri oh neat, I hadn't seen "verify" before, what a great addition!

**Comment by nathwill** [comment]
these changes are out in 0.3.0. i'll leave this open for a bit longer in case there's further feedback, but so far i'm pretty happy with where this ended up.

**Comment by nathwill** [comment]
what this has been working towards is [finally here](https://github.com/nathwill/chef-haproxy-ng/pull/14) :metal:
