### ISSUE TITLE
haproxy.cfg shouldn't be world readable 

### ISSUE THREAD

**Issue by szymonpk** [nathwill/chef-haproxy-ng#18]
I'm not sure what is you opinion on this matter, but I think [haproxy.cfg](https://github.com/nathwill/chef-haproxy-ng/blob/master/libraries/chef_haproxy_instance.rb#L142) shouldn't be world readable, plaintext/hashes may be stored there. Owner/group should be changed to haproxy to allow process access file.

**Comment by nathwill** [comment]
interestingly, the package maintainers seem to leave it root:root, with 644 permissions, but i tend to agree with you about world-readability not being wonderful... i'll see what some simple options might be.

**Comment by nathwill** [comment]
@szymonpk so haproxy does this awesome thing where it starts out as root and then suid's to the user configured in the haproxy config file, so we don't actually have to change the ownership, just the permissions to revoke world-readability, and presto-changeo, things are looking better (or at least, less scary).

i went ahead and applied that change in https://github.com/nathwill/chef-haproxy-ng/commit/6ab9eda151c280cacda4ad53fa2caf144bd8c960, which, along with an update to the newly released stable 1.5.13 for source-installs is going out momentarily in v1.0.0. :tada: 

thanks for bringing this up, and let me know if you run into anything else!
