### ISSUE TITLE
find more maintainers

### ISSUE THREAD

**Issue by nathwill** [nathwill/chef-haproxy-ng#24]
would love to find some additional maintainers for this cookbook to help upgrade the bus factor, anybody interested?

**Comment by mburns** [comment]
@nathwill I've only recently started using this cookbook, but would be happy to lend a hand.

**Comment by nathwill** [comment]
Thanks @mburns, i'm adding you as a collaborator. i'm `nathwill` on IRC if you need to find me for chats or anything :)
