### ISSUE TITLE
How does one implement this cookbook

### ISSUE THREAD

**Issue by dkhaws77** [nathwill/chef-haproxy-ng#28]
I've been trying to implement this but have had no luck in getting the config file updated.  My approach is to include the haprox-ng cookbook in my own and then use frontend and backend resources to update the config file.  But all I get in the file is the below entries:

`global 

  daemon 

  user haproxy 

  group haproxy 

  pidfile /var/run/haproxy.pid 

  maxconn 50000 
`
Please provide me with some guidance on how to implement this and what I might be doing wrong.

**Comment by nathwill** [comment]
if you're using the default `haproxy_instance` resource from the default recipe, you'll need to set the `default['haproxy']['proxies']` attribute to an array containing the list of proxies (e.g. frontends/backends) you want included.

so for example if you have a `haproxy_frontend[http]`, and a `haproxy_backend[web_servers]`, you would set the attribute to `%w( http web_servers )`.
